name: Feature request
description: Create a feature request
title: My feature request
labels: []
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. When I do [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional contex
      description: Add any other context or screenshots about the feature request here.
  - type: input
    attributes:
      label: Search terms
      description: Help other people discover your feature request by writing words they might search for.
