name: Feature request
description: Create a feature request
title: ""
labels: []
body:
  - type: textarea
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is.
    placeholder: Ex. When I do [...]
  - type: textarea
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  - type: textarea
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    label: Additional contex
    description: Add any other context or screenshots about the feature request here.
  - type: input
    label: Search terms
    description: Help other people discover your feature request by writing words they might search for.
