name: Publish summary

on:
  issues:
    types: [opened, closed, transferred, reopened, deleted, edited]
    schedule:
      - cron: "0 * * * *"

jobs:
  publish-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate feature requests summary
        uses: ./.github/actions/summary-generator
        id: generate_feature_requests_summary

      - name: Update feature requests comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          repository: scalameta/metals
          # https://github.com/scalameta/metals/issues/707#issuecomment-488311466
          comment-id: 488311466
          body:
            ${{ steps.generate_feature_requests_summary.outputs.comment-body }}
          edit-mode: replace
          token: ${{ secrets.SCALAMETA_BOT_GITHUB_TOKEN }}
